AWSTemplateFormatVersion: '2010-09-09'
Description: Template to automatically setup Qualys Insights in AWS Security Hub
Metadata:
  Author: "Sadanand Nerurkar"
  Version: "1.0"
  Updated: "12 Mar 2020"
  Version Comments: "Created as per customer request"
Resources:
  AWSFunction:
    DependsOn: LambdaExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            import boto3
            import cfnresponse 
            sec_hub_client = boto3.client('securityhub')
            filters_1 = {'SeverityLabel':[{'Value':'CRITICAL', 'Comparison': 'EQUALS'},],
           'RecordState':[{ 'Value': 'ACTIVE', 'Comparison':'EQUALS'},],
           'CompanyName':[{'Value':'Qualys', 'Comparison':'EQUALS'}]}

            filters_2 = {'ProductFields':[{'Key': 'isExploitable','Value':'true', 'Comparison': 'EQUALS'},],
           'RecordState':[{ 'Value': 'ACTIVE', 'Comparison':'EQUALS'},],
           'CompanyName':[{'Value':'Qualys', 'Comparison':'EQUALS'}]}

            filters_3 = {'ProductFields':[{'Key': 'isPatchAvailable','Value':'true', 'Comparison': 'EQUALS'},],
             'RecordState':[{ 'Value': 'ACTIVE', 'Comparison':'EQUALS'},],
           'CompanyName':[{'Value':'Qualys', 'Comparison':'EQUALS'}]}

            filters_4 = {'RecordState':[{ 'Value': 'ACTIVE', 'Comparison':'EQUALS'},],
           'CompanyName':[{'Value':'Qualys', 'Comparison':'EQUALS'}]}

            insight_response_1 = sec_hub_client.create_insight(Name="Instances with Critical vuln-Qualys", Filters=filters_1, GroupByAttribute='ResourceType')
            insight_response_2 = sec_hub_client.create_insight(Name='Instances with Exploitable Vuln-Qualys', Filters=filters_2, GroupByAttribute='ResourceType')
            insight_response_3 = sec_hub_client.create_insight(Name='Instances with missing patches-Qualys', Filters=filters_3, GroupByAttribute='ResourceType')
            insight_response_4 = sec_hub_client.create_insight(Name='AMIs with highest number of Vulns-Qualys', Filters=filters_4, GroupByAttribute='ResourceAwsEc2InstanceImageId')
            responseData = {}
            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
      Description: Lambda Function to create a Qualys Insights in AWS Security Hub
      FunctionName: QualysInsightsLambdaFunction
      Handler: index.lambda_handler
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Runtime: python3.6
      Timeout: '120'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: QualysInsightsLambdaexecRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - iam:CreateRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - securityhub:CreateInsight
                Resource: '*'
  CustomResource:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !GetAtt 'AWSFunction.Arn'    